Error from server (AlreadyExists): pods "devops" already exists
NAME     READY   STATUS    RESTARTS      AGE
devops   1/1     Running   1 (19m ago)   26m
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

voclabs:~/environment/DevOps_Microservices (main) $ kubectl logs devops
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 125-706-748
[2022-08-09 16:56:59,184] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-09 16:56:59,202] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 16:56:59,212] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 16:56:59,216] INFO in app: Prediction: 
[20.35373177134412]
127.0.0.1 - - [09/Aug/2022 16:56:59] "POST /predict HTTP/1.1" 200 -
[2022-08-09 17:09:52,655] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-09 17:09:52,667] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 17:09:52,677] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 17:09:52,681] INFO in app: Prediction: 
[20.35373177134412]
127.0.0.1 - - [09/Aug/2022 17:09:52] "POST /predict HTTP/1.1" 200 -